FROM openjdk:17-jdk-slim
WORKDIR /app

# Copy the built JAR file into the container
COPY target/EurekaServer-0.0.1-SNAPSHOT.jar app.jar

# Expose Eureka default port
EXPOSE 8761

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
